// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcrJ4Jdp2vycE3evac1ZgjdRfESYvvGN8',
    appId: '1:224739380277:web:a7a4135ddd74dcc831757c',
    messagingSenderId: '224739380277',
    projectId: 'devworld-portal',
    authDomain: 'devworld-portal.firebaseapp.com',
    storageBucket: 'devworld-portal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBohRuy69GLqLjGviUNrPtmdyljb0-f0bY',
    appId: '1:224739380277:android:e83d1e2eb1992dd131757c',
    messagingSenderId: '224739380277',
    projectId: 'devworld-portal',
    storageBucket: 'devworld-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkqtZQwdQssvOLCt6F6NA3oDFefRIf2ck',
    appId: '1:224739380277:ios:c6fd248ac8aafca031757c',
    messagingSenderId: '224739380277',
    projectId: 'devworld-portal',
    storageBucket: 'devworld-portal.appspot.com',
    iosClientId: '224739380277-8uip608205hmdvqh62hhq7p9mbiavv2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkqtZQwdQssvOLCt6F6NA3oDFefRIf2ck',
    appId: '1:224739380277:ios:c6fd248ac8aafca031757c',
    messagingSenderId: '224739380277',
    projectId: 'devworld-portal',
    storageBucket: 'devworld-portal.appspot.com',
    iosClientId: '224739380277-8uip608205hmdvqh62hhq7p9mbiavv2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.portal',
  );
}
